MVC3/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC3.Models;

namespace MVC3.Controllers
{
  public class ScheduleController : Controller
  {
    //
    // GET: /Schedule/
    public ActionResult Index(string yearFilter, string quarterFilter)
    {
      if (yearFilter == null)
        yearFilter = "";

      if (quarterFilter == null)
        quarterFilter = "";

      string student_id = Session["id"].ToString();

      PLStudent student = StudentClientService.GetStudentDetail(student_id);
      ViewBag.student = student;

      List<PLSchedule> scheduleList = ScheduleClientService.GetScheduleList(yearFilter, quarterFilter);

      int year = DateTime.Now.Year;
      int previousYear = year - 1;
      int nextYear = year + 1;

      // only display the current year, previous year, and next year as selections
      List<SelectListItem> YearList = new List<SelectListItem>();
      YearList.Add(new SelectListItem { Text = "All Years", Value = "" });
      YearList.Add(new SelectListItem { Text = previousYear.ToString(), Value = previousYear.ToString() });
      YearList.Add(new SelectListItem { Text = year.ToString(), Value = year.ToString() });
      YearList.Add(new SelectListItem { Text = nextYear.ToString(), Value = nextYear.ToString() });

      // these usually comes from the database... 
      List<SelectListItem> QuarterList = new List<SelectListItem>();
      QuarterList.Add(new SelectListItem { Text = "All Quarters", Value = "" });
      QuarterList.Add(new SelectListItem { Text = "Fall", Value = "Fall" });
      QuarterList.Add(new SelectListItem { Text = "Winter", Value = "Winter" });
      QuarterList.Add(new SelectListItem { Text = "Spring", Value = "Spring" });
      QuarterList.Add(new SelectListItem { Text = "Summer 1", Value = "Summer 1" });
      QuarterList.Add(new SelectListItem { Text = "Summer 2", Value = "Summer 2" });

      ViewBag.YearList = YearList;
      ViewBag.QuarterList = QuarterList;

      return View("Index", scheduleList);
    }

    public ActionResult Filter(string yearFilter, string quarterFilter)
    {
      if (yearFilter == null)
        yearFilter = "";

      if (quarterFilter == null)
        quarterFilter = "";

      string student_id = Session["id"].ToString();

      PLStudent student = StudentClientService.GetStudentDetail(student_id);
      ViewBag.student = student;

      List<PLSchedule> scheduleList = ScheduleClientService.GetScheduleList(yearFilter, quarterFilter);

      return Json(scheduleList);
    }
  }
}

MVC3/Views/Schedule/Index.cshtml
@model List<MVC3.Models.PLSchedule>

@{
  ViewBag.Title = "Index";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@Html.ActionLink("Refresh", "Index")
<br />
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@Html.Partial("StudentEnrollment", (MVC3.Models.PLStudent)ViewBag.student)

@using (Html.BeginForm("Index", "Schedule"))
{
      <h2>Schedule</h2>
      <table>
          <tr>
              <th></th>
              <th>
                  Schedule ID
              </th>
              <th>
                @Html.DropDownList("yearFilter", (List<SelectListItem>)ViewData["YearList"], new { onchange = "this.form.submit()" })
              </th>
              <th>
                @Html.DropDownList("quarterFilter", (List<SelectListItem>)ViewData["QuarterList"], new { onchange = "this.form.submit()" })
              </th>
              <th>
                  Session
              </th>
              <th>
                  Course Title
              </th>
              <th>
                  Description
              </th>
          </tr>
          @foreach (var item in Model) { 
          <tr>
              <td>
                  @Html.ActionLink("Add", "Enroll", "Student", new { schedule_id = item.schedule_id }, null) 
              </td>
              <td>
                  @item.schedule_id
              </td>
              <td>
                  @item.year
              </td>
              <td>
                  @item.quarter
              </td>
              <td>
                  @item.session
              </td>
              <td>
                  @item.course_title
              </td>
              <td>
                  @item.course_description
              </td>
          </tr>
          }
      </table>
}